name: KEMM30
channels:
  - conda-forge
  - omnia
  - anaconda 
dependencies:
  - python=3.*
  - lxml=4.3
  - openpyxl=2.6
  - mdtraj
  - nglview
  - pandas=0.25
  - scipy
  - numpy
  - matplotlib=3.0.2
  - ipywidgets
  - biopython
  - brewer2mpl
  - rdkit
  - uncertainties
  - lmfit
  - pip
  - pip: 
     - git+https://github.com/jjhelmus/nmrglue
