name: KEMM30
channels:
  - conda-forge
  - teokem
  - anaconda 
dependencies:
  - python=3
  - pip
  - pip: 
     - git+https://github.com/jjhelmus/nmrglue
     - lmfit 
     - ipympl 
     - lxml 
     - nglview
     - ipywidgets 
     - brewer2mpl 
     - rdkit 
     - ffmpeg 
     - nmrglue
