name: KEMM30
channels:
  - conda-forge
  - teokem
  - omnia
  - anaconda 
dependencies:
  - python=3.9
  - lxml=4
  - openpyxl=3
  - mdtraj=1
  - nglview=3
  - pandas=1
  - scipy=1
  - numpy=1
  - matplotlib=3
  - ipywidgets=7
  - faunus
  - brewer2mpl=1
  - rdkit=2022.03.5
  - uncertainties=3
  - lmfit=1
  - ffmpeg=5
  - pip
  - pip: 
     - git+https://github.com/jjhelmus/nmrglue
