name: KEMM30
channels:
  - conda-forge
  - teokem
  - omnia
  - anaconda 
dependencies:
  - python=3
  - lxml=4.3
  - openpyxl=2.6
  - mdtraj=1.9
  - nglview=3.0.3
  - pandas=1.4
  - scipy=1.7
  - numpy=1.21
  - matplotlib=3.5
  - ipywidgets=7.7.2
  - faunus
  - biopython=1.79
  - brewer2mpl=1.4.1
  - rdkit=2022.03.5
  - uncertainties=3.1
  - lmfit=1.0.3
  - ffmpeg=5.1
  - pip
  - pip: 
     - git+https://github.com/jjhelmus/nmrglue
