name: KEMM30
channels:
  - conda-forge
  - teokem
  - anaconda 
dependencies:
  - python=3
  - lmfit
  - ipympl
  - lxml 
  - nglview
  - ipywidgets 
  - brewer2mpl 
  - rdkit 
  - ffmpeg 
  - pip
  - pip: 
     - git+https://github.com/jjhelmus/nmrglue
