name: KEMM30
channels:
  - conda-forge
  - omnia
  - anaconda 
dependencies:
  - python=3.*
  - lxml=4.3
  - openpyxl=2.6
  - mdtraj
  - nglview
  - pandas
  - scipy
  - numpy
  - jupyter
  - matplotlib
  - ipywidgets=7.5.1
  - biopython
  - brewer2mpl
  - widgetsnbextension
  - jupyter_contrib_nbextensions
  - rdkit
  - uncertainties
  - lmfit
  - ffmpeg 
  - pip
  - pip: 
     - git+https://github.com/jjhelmus/nmrglue
